version: "3.9"
services:
  app:
    build:
      args:
        user: helpdesk-justisia
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: helpdesk-justisia
    container_name: helpdesk-justisia-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - justisia-helpdesk-net

  nginx:
    image: nginx:alpine
    container_name: helpdesk-justisia-nginx
    restart: unless-stopped
    ports:
      - 8989:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - justisia-helpdesk-net
  db:
      image: mariadb:10.5
      container_name: db-justisia-helpdesk-erm
      restart: unless-stopped
      environment:
          MYSQL_ROOT_PASSWORD: iniP@assword
          MYSQL_DATABASE: helpdesk
          MYSQL_USER: root
          MYSQL_PASSWORD: iniP@assword
      volumes:
          - ./db_data:/var/lib/mysql
      networks:
          - justisia-helpdesk-net
      ports:
          - "8990:3306"
networks:
  justisia-helpdesk-net:
    driver: bridge
